package tfprovider

import (
	"sort"
	"testing"

	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

// The registry renders these descriptions verbatim. An attribute without one
// shows as a bare name and type in a table, which is what most of the
// data-source pages looked like — 147 attributes with nothing beside them.
// Once published, every regeneration ships the gap again, so it is cheaper to
// fail here than to notice it on the website.
//
// This walks the protocol 6 schema rather than the framework types, because
// that is precisely what tfplugindocs reads.

// bareAttributes names every attribute in a block, and in its nested blocks,
// that carries no description.
func bareAttributes(prefix string, block *tfprotov6.SchemaBlock) []string {
	if block == nil {
		return nil
	}

	var bare []string

	for _, attr := range block.Attributes {
		if attr.Description == "" {
			bare = append(bare, prefix+"."+attr.Name)
		}

		if attr.NestedType != nil {
			for _, nested := range attr.NestedType.Attributes {
				if nested.Description == "" {
					bare = append(bare, prefix+"."+attr.Name+"."+nested.Name)
				}
			}
		}
	}

	for _, nested := range block.BlockTypes {
		bare = append(bare, bareAttributes(prefix+"."+nested.TypeName, nested.Block)...)
	}

	return bare
}

// TestEverySchemaAttributeIsDescribed covers the provider block, every
// resource and every data source in one pass, so a new one cannot be added
// undocumented.
func TestEverySchemaAttributeIsDescribed(t *testing.T) {
	t.Parallel()

	h := newHarness(t)

	resp, err := h.srv.GetProviderSchema(h.ctx, &tfprotov6.GetProviderSchemaRequest{})
	if err != nil {
		t.Fatalf("GetProviderSchema: %v", err)
	}

	var bare []string

	bare = append(bare, bareAttributes("provider", resp.Provider.Block)...)

	for name, schema := range resp.ResourceSchemas {
		bare = append(bare, bareAttributes(name, schema.Block)...)
	}

	for name, schema := range resp.DataSourceSchemas {
		bare = append(bare, bareAttributes(name, schema.Block)...)
	}

	// timeouts is generated by terraform-plugin-framework-timeouts; its
	// description is not ours to set.
	exempt := map[string]bool{"gigahost_server.timeouts": true}

	sort.Strings(bare)

	for _, name := range bare {
		if exempt[name] {
			continue
		}

		t.Errorf("%s has no description; it renders as an empty cell on the registry page", name)
	}
}
